from pathlib import Path
paths = [Path(''assets/index-Cc6wxg0n.js''), Path(''dist/assets/index-Cc6wxg0n.js'')]
old = r"const MT=\"https://custodiabackend-prod.idsf.com.br/api\",NT={accept:\"application/json\",Ambiente:\"custodia\",Token:\"DHQzckJ0TGWHiFxaVuUlmrBLWXwuejrtSAT0Mf47gvclZ5GKY543iYKNeLfqlzngXH0YcKGLe4qyv0avru3xeVGBp9yUQKKKlSyJ\"};async function C3(){const e=await fetch(`${MT}/ZiSign/eventos-unicos`,{headers:NT});if(!e.ok)throw new Error(\"Failed to fetch module events\");const t=await e.json();return Array.isArray(t)?t:t.data||[]}async function $3(){const t=await fetch(`${MT}/ZiSign/TV?cnpjCertificadora=54638076000176`,{headers:NT});if(!t.ok)throw new Error(\"Failed to fetch operations\");const r=await t.json();return(Array.isArray(r)?r:r.data||[]).filter(i=>i.nomeFundo!==\"Zitec FIDC\").map(i=>{const o=(i.hrAtraso||\"00:00:00\").toString().trim(),[a,s,l]=o.split(\":\" ).map(Number),u=(a||0)*3600+(s||0)*60+(l||0);return{...i,atrasoSeg:u,atrasoStr:o}})}"
new = r"const MT=\"https://custodiabackend-prod.idsf.com.br/api\",NT={accept:\"application/json\",Ambiente:\"custodia\",Token:\"DHQzckJ0TGWHiFxaVuUlmrBLWXwuejrtSAT0Mf47gvclZ5GKY543iYKNeLfqlzngXH0YcKGLe4qyv0avru3xeVGBp9yUQKKKlSyJ\"},OT=new Map;async function C3(){const e=await fetch(`${MT}/ZiSign/eventos-unicos`,{headers:NT});if(!e.ok)throw new Error(\"Failed to fetch module events\");const t=await e.json();return Array.isArray(t)?t:t.data||[]}async function $3(){const t=await fetch(`${MT}/ZiSign/TV?cnpjCertificadora=54638076000176`,{headers:NT});if(!t.ok)throw new Error(\"Failed to fetch operations\");const r=await t.json(),n=Array.isArray(r)?r:r.data||[],i=n.filter(s=>s.nomeFundo!==\"Zitec FIDC\"),o=Date.now(),a=new Set;const l=i.map(s=>{const d=s.idOperacaoRecebivel??s.idOperacao??s.id??`${s.nomeFundo}-${s.cnpjFundo??\"\"}`;a.add(d),OT.has(d)||OT.set(d,o);const u=Math.max(0,Math.floor((Date.now()-OT.get(d))/1e3)),f=String(Math.floor(u/3600)).padStart(2,\"0\"),c=String(Math.floor(u%3600/60)).padStart(2,\"0\"),p=String(u%60).padStart(2,\"0\");return{...s,atrasoSeg:u,atrasoStr:`${f}:${c}:${p}`}});return OT.forEach((s,d)=>{a.has(d)||OT.delete(d)}),l}"
for path in paths:
    text = path.read_text(encoding='utf-8')
    if old not in text:
        print(f"Pattern not found in {path}")
        continue
    path.write_text(text.replace(old, new), encoding='utf-8')
    print(f"Updated {path}")
